import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { type CallToolResult } from "@modelcontextprotocol/sdk/types.js";

// AUTO-GENERATED by NexaScience/mcp-generator. Do not edit by hand.
void z;



export const getServer = (): McpServer => {
  const server = new McpServer(
    { name: "mcp-dice-demo", version: "1.0.0" },
    { capabilities: {} },
  );

  const text = (s: string): CallToolResult => ({ content: [{ type: "text", text: s }] });
  void text;

  server.registerTool(
    "roll_dice",
    {
      title: "Roll Dice",
      description: "Roll one or more dice with a configurable number of sides. Returns the array of individual roll results and their total sum.",
      inputSchema: { sides: z.number().int().min(2).default(6).describe('Number of sides per die'), count: z.number().int().min(1).max(100).default(1).describe('How many dice to roll') },
    },
    async (args): Promise<CallToolResult> => {
      void args;
      const sides = input.sides ?? 6;
const count = input.count ?? 1;
const rolls = [];
for (let i = 0; i < count; i++) {
  rolls.push(Math.floor(Math.random() * sides) + 1);
}
const total = rolls.reduce((a, b) => a + b, 0);
const result = { sides, count, rolls, total };
return { content: [{ type: 'text', text: JSON.stringify(result) }] };
    },
  );

  return server;
};
